[package]
name = "cow-dice-rs"
description = "Game dice"
version = "0.1.0"
edition = "2021"
authors = ["shadowcow84@gmail.com"]
license = "MIT"

[dependencies]
rand = "0.8.5"

[lib]
name = "cow_dice_rs"